name: Publish package to GitHub Packages
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@pierre-couturier-kelkun'
      # Install dependencies
      - run: npm ci

      # Build the package (assuming your package build process creates files in `./build/package`)
      - run: npm run package

      # Change to the directory where the built package is located and ensure it contains `package.json`
      - run: |
          ls ./build/package  # List files in the build directory to ensure all files are present
          cd ./build/package
          ls  # Verify the content after moving into the build folder
          npm publish  # Publish the package from the build directory
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
